# Generated by Django 4.2.7 on 2023-12-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
