# Generated by Django 4.2.7 on 2023-12-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_nombre_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
