# Generated by Django 4.2.7 on 2024-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_apellidos_alter_user_nombre_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('especialista', 'Especialista'), ('invitado', 'Invitado')], default='invitado', max_length=20),
        ),
    ]
