# Generated by Django 4.2.7 on 2024-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_apellidos_alter_user_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
