# Generated by Django 4.2.7 on 2024-02-22 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del profesor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Nombre del profesor')),
                ('ci', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\w{11}$', 'El CI debe tener exactamente 11 caracteres.')], verbose_name='CI del profesor')),
                ('titulo_recurso', models.CharField(max_length=255, verbose_name='Titulo del Recurso')),
                ('tipo_publicacion', models.CharField(choices=[('LIBRO', 'Libro'), ('CAPITULO', 'Capítulo'), ('EPIGRAFE', 'Epígrafe'), ('ARTICULO', 'Artículo')], max_length=255, verbose_name='Tipo de la publicación')),
                ('lugar_pub', models.CharField(max_length=255, verbose_name='Lugar de Publicación')),
                ('formato', models.CharField(choices=[('IMPRESO', 'Libro Impreso'), ('DIGITAL', 'Libro Digital'), ('RIMPRESA', 'Revista Impresa'), ('DDIGITAL', 'Revista Digital')], max_length=255, verbose_name='Formato del Artículo')),
                ('issn', models.CharField(max_length=255, unique=True, verbose_name='issn de revista impresa')),
                ('e_issn', models.CharField(max_length=255, unique=True, verbose_name='issn electronico de revista digital')),
                ('isbn', models.CharField(max_length=255, verbose_name='Código único del libro')),
                ('url', models.CharField(max_length=255, verbose_name='Url del Sitio Web')),
                ('database', models.BooleanField(default=False, verbose_name='base de datos')),
                ('cd_rom', models.BooleanField(default=False, verbose_name='CD-ROM/DVD')),
                ('tomo', models.CharField(max_length=255, verbose_name='Tomo')),
                ('folio', models.CharField(max_length=255, verbose_name='Folio')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
