# Generated by Django 4.2.7 on 2024-03-02 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='cd_rom',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='database',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='formato',
        ),
        migrations.AddField(
            model_name='profesor',
            name='base_de_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cdrom_dvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo_recurso',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='e_issn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='folio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='isbn',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='issn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo_publicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='titulo_recurso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tomo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
