# Generated by Django 4.2.7 on 2024-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0004_alter_profesor_titulo_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
