# Generated by Django 4.2.7 on 2024-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0006_avales_tuto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha',
            field=models.DateField(),
        ),
    ]
