# Generated by Django 4.2.7 on 2024-06-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0008_avales_biblio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalUnificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aval', models.CharField(choices=[('prof', 'Publicación'), ('tuto', 'Tutoría'), ('bibl', 'Biblioteca')], max_length=10)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ['fecha'],
                'managed': False,
            },
        ),
    ]
