# Generated by Django 4.2.7 on 2024-06-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0009_avalunificado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvalUnificado',
        ),
    ]
