# Generated by Django 4.2.7 on 2024-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0012_remove_avales_tuto_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avales_biblio',
            name='niv_act',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
