# Generated by Django 4.2.7 on 2024-06-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0014_remove_avales_biblio_titulo_recurso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avales_biblio',
            old_name='rev_biblio',
            new_name='rev_bilio',
        ),
    ]
