# Generated by Django 4.2.7 on 2024-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0016_avales_tuto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grupo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
