# Generated by Django 4.2.7 on 2024-07-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0017_profesor_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'autores',
            },
        ),
    ]
