# Generated by Django 4.2.7 on 2024-07-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0018_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellidos_autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamento_autor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre_autor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
