# Generated by Django 4.2.7 on 2024-07-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0021_profesor_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='profesor.autor'),
        ),
    ]
