# Generated by Django 4.2.7 on 2024-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0024_alter_profesor_e_issn_alter_profesor_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='url',
            field=models.CharField(blank=True),
        ),
    ]
